apiVersion: apps/v1

kind: Deployment

metadata:
  name: internal-deployment
  labels:
    app: internal
    tier: backend

spec:
  template:
    metadata:
      name: internal-pod
      labels:
        app: internal

    spec:
      containers:
        - name: internal-container
          image: shakhanna/internal:2.0

  replicas: 3
  selector:
    matchLabels:
      app: internal
